/* COPYRIGHT (C) HARRY CLARK 2023 */

/* MY FRONTEND FOR GUI APPS IN C */

/* THIS FILE SERVES TO PROVIDE A ONE-FILE SOLUTION FOR ACCESSING */
/* THE FUNCTIONALITY OF THE SDL LIBRARY */

/* WHILE PROVIDING MY OWN FUNCTIONALITY SUCH AS CREATING MY OWN TYPES */
/* IN RELATION TO MY CURRENT PROJECTS */

#ifndef SDL_BASE
#define SDL_BASE

/* SYSTEM INCLUDES */

#include <memory.h>
#include <stdlib.h>

#if defined(USE_SDL)
#define USE_SDL
#else

#define USE_SDL
#include <SDL3/SDL.h>

#define     SDL_WRAPPER_OBJECT(NAME, TYPE, DECONSTRUCT) \
SDL_WRAPPER_OBJECT(Window, SDL_Window, SDL_DestroyWindow);

#endif

#endif
