/* COPYRIGHT (C) HARRY CLARK 2024 */

/* FRONTEND FOR GUI APPLICATIONS IN C */

/* THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF THE FRONTEND */
/* ENCORPETATING TYPES AND METHODS PERTAINING TOWARDS THE GENERAL PRE-REQUISITIES */

/* NESTED INCLUDES */

#include "frontend.h"

/* SYSTEM INCLUDES */

#include <limits.h>
#include <malloc.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#ifdef USE_SDL

/* INITIALISE THE MAIN FRONTEND WINDOW BY USING THE PRE-REQUISITIES FROM */
/* THE INCLUDED HEADER FILES */

/* I HAVE OPTED TO USE IFDEF AS THE DECLARATIVE MACRO TO INCLUDE ALL OF THE */
/* SDL HEADERS AS OPPOSED TO INCLUDING THEM ONE BY ONE */

STATIC
int FRONTEND_INIT(int argc, char** argv)
{
    struct FRONTEND* FRONTEND_BASE;

    /* USING SDL PRE-REQUISITIES TO DETERMINE WHICH SUBSYSTEMS ARE GOING TO BE USED */
    /* WITHIN THE PROGRAM */

    if(SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_EVENTS | SDL_INIT_GAMECONTROLLER))
        SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Failed to Initialise SDL Media Layer", "%s", 0);
    else
        FRONTEND_BASE->FRONTEND_WIN = 1, malloc(sizeof(FRONTEND_BASE->FRONTEND_WIN));
        INIT_WINDOW(FRONTEND_BASE->FRONTEND_WIN, "MEGA DRIVE EMULATOR", 0, 0, 0, 0);

    SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "1");
}

/* FREE UP/DEINITIALISE MEMORY FROM THE PROGRAM */
/* AS AND WHEN IT ISN'T BEING USED */

STATIC
void FRONTEND_FREE(void)
{
    struct FRONTEND* FRONTEND_BASE;
    struct MD_CONFIG* MD;

    if(FRONTEND_BASE->FRONTEND_TEXTURE != NULL)
        SDL_DestroyTexture(FRONTEND_BASE->FRONTEND_TEXTURE);

    free(MD->STATE.M68K);
    free(MD->STATE.Z80);
}


#endif
