/* COPYRIGHT (C) HARRY CLARK 2024 */

/* MINIMAL FRONTEND APPLICATION USING SDL AND IMGUI */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING THE */
/* INITIALISATION AND OF THE APPLICATION WINDOW */

/* NESTED INCLUDES */

using namespace FRONTEND;

#include "window.hpp"

/* DETERMINE THE DPI WINDOW SCALE TO BE ABLE TO ACCURATELY SCALE THE WINDOW */
/* IN ACCORDANCE WITH RELATIVE MOUSE SPEEDS */

float WINDOW::GET_DPI_WINDOW_SCALE()
{
	WINDOW* WINDOW_BASE;

	SDL_GetWindowSize(WINDOW_BASE->GET_WINDOW(), &WINDOW_BASE->WINDOW_WIDTH, &WINDOW_BASE->WINDOW_HEIGHT);

	WINDOW_BASE->DPI_X = static_cast<float>(WINDOW_BASE->RENDERER_WIDTH) / std::max(1, WINDOW_BASE->WINDOW_WIDTH);
	WINDOW_BASE->DPI_Y = static_cast<float>(WINDOW_BASE->RENDERER_HEIGHT) / std::max(1, WINDOW_BASE->WINDOW_HEIGHT);
	WINDOW_BASE->DPI_SCALE = std::min(DPI_X, DPI_Y);

	return (WINDOW_BASE->DPI_SCALE < 1.0f) ? 1.0f : WINDOW_BASE->DPI_SCALE;
}
